export interface Ward { id: string; name: string; }
export interface Lga { id: string; name: string; wards: Ward[]; }
export interface State { id: string; name: string; lgas: Lga[]; }

function makeLga(stateId: string, lgaName: string, wardNames: string[]): Lga {
  const lgaId = `${stateId}-${lgaName.toLowerCase().replace(/[^a-z0-9]/g, '-')}`;
  return {
    id: lgaId,
    name: lgaName,
    wards: wardNames.map((w, i) => ({ id: `${lgaId}-w${i + 1}`, name: w })),
  };
}

function makeState(id: string, name: string, lgaData: [string, string[]][]): State {
  return { id, name, lgas: lgaData.map(([lgaName, wards]) => makeLga(id, lgaName, wards)) };
}

export const GEO_DATA: State[] = [
  makeState('abia', 'Abia', [
    ['Aba North', ['Ariaria', 'Cemetery', 'Eziama', 'Industrial', 'Ogbor Hill', 'Old GRA', 'Osisioma', 'Umuola', 'Uratta']],
    ['Aba South', ['Aba South I', 'Aba South II', 'Aba South III', 'Aba South IV', 'Aba South V', 'Aba South VI']],
    ['Arochukwu', ['Arochukwu I', 'Arochukwu II', 'Arochukwu III', 'Arochukwu IV', 'Arochukwu V']],
    ['Bende', ['Bende I', 'Bende II', 'Bende III', 'Bende IV', 'Bende V', 'Bende VI']],
    ['Ikwuano', ['Ikwuano I', 'Ikwuano II', 'Ikwuano III', 'Ikwuano IV', 'Ikwuano V']],
    ['Isiala Ngwa North', ['Isiala Ngwa North I', 'Isiala Ngwa North II', 'Isiala Ngwa North III', 'Isiala Ngwa North IV']],
    ['Isiala Ngwa South', ['Isiala Ngwa South I', 'Isiala Ngwa South II', 'Isiala Ngwa South III', 'Isiala Ngwa South IV']],
    ['Isuikwuato', ['Isuikwuato I', 'Isuikwuato II', 'Isuikwuato III', 'Isuikwuato IV']],
    ['Obi Ngwa', ['Obi Ngwa I', 'Obi Ngwa II', 'Obi Ngwa III', 'Obi Ngwa IV', 'Obi Ngwa V']],
    ['Ohafia', ['Ohafia I', 'Ohafia II', 'Ohafia III', 'Ohafia IV', 'Ohafia V', 'Ohafia VI']],
    ['Osisioma', ['Osisioma I', 'Osisioma II', 'Osisioma III', 'Osisioma IV', 'Osisioma V']],
    ['Ugwunagbo', ['Ugwunagbo I', 'Ugwunagbo II', 'Ugwunagbo III', 'Ugwunagbo IV']],
    ['Ukwa East', ['Ukwa East I', 'Ukwa East II', 'Ukwa East III', 'Ukwa East IV']],
    ['Ukwa West', ['Ukwa West I', 'Ukwa West II', 'Ukwa West III', 'Ukwa West IV']],
    ['Umuahia North', ['Umuahia North I', 'Umuahia North II', 'Umuahia North III', 'Umuahia North IV', 'Umuahia North V']],
    ['Umuahia South', ['Umuahia South I', 'Umuahia South II', 'Umuahia South III', 'Umuahia South IV']],
    ['Umu Nneochi', ['Umu Nneochi I', 'Umu Nneochi II', 'Umu Nneochi III', 'Umu Nneochi IV']],
  ]),
  makeState('adamawa', 'Adamawa', [
    ['Demsa', ['Demsa I', 'Demsa II', 'Demsa III', 'Demsa IV', 'Demsa V']],
    ['Fufure', ['Fufure I', 'Fufure II', 'Fufure III', 'Fufure IV']],
    ['Ganye', ['Ganye I', 'Ganye II', 'Ganye III', 'Ganye IV', 'Ganye V']],
    ['Gayuk', ['Gayuk I', 'Gayuk II', 'Gayuk III']],
    ['Gombi', ['Gombi I', 'Gombi II', 'Gombi III', 'Gombi IV']],
    ['Grie', ['Grie I', 'Grie II', 'Grie III']],
    ['Hong', ['Hong I', 'Hong II', 'Hong III', 'Hong IV', 'Hong V']],
    ['Jada', ['Jada I', 'Jada II', 'Jada III', 'Jada IV']],
    ['Lamurde', ['Lamurde I', 'Lamurde II', 'Lamurde III', 'Lamurde IV']],
    ['Madagali', ['Madagali I', 'Madagali II', 'Madagali III', 'Madagali IV']],
    ['Maiha', ['Maiha I', 'Maiha II', 'Maiha III', 'Maiha IV']],
    ['Mayo Belwa', ['Mayo Belwa I', 'Mayo Belwa II', 'Mayo Belwa III', 'Mayo Belwa IV', 'Mayo Belwa V']],
    ['Michika', ['Michika I', 'Michika II', 'Michika III', 'Michika IV']],
    ['Mubi North', ['Mubi North I', 'Mubi North II', 'Mubi North III', 'Mubi North IV', 'Mubi North V']],
    ['Mubi South', ['Mubi South I', 'Mubi South II', 'Mubi South III', 'Mubi South IV']],
    ['Numan', ['Numan I', 'Numan II', 'Numan III', 'Numan IV', 'Numan V']],
    ['Shelleng', ['Shelleng I', 'Shelleng II', 'Shelleng III', 'Shelleng IV']],
    ['Song', ['Song I', 'Song II', 'Song III', 'Song IV', 'Song V']],
    ['Toungo', ['Toungo I', 'Toungo II', 'Toungo III']],
    ['Yola North', ['Doubeli', 'Jambutu', 'Karewa', 'Limawa', 'Luggere', 'Nassarawo', 'Yolde Pate']],
    ['Yola South', ['Bole Yolde', 'Daware', 'Farang', 'Mbamba', 'Namtari', 'Ngurore', 'Wuro Chekke']],
  ]),
  makeState('akwa-ibom', 'Akwa Ibom', [
    ['Abak', ['Abak I', 'Abak II', 'Abak III', 'Abak IV', 'Abak V']],
    ['Eastern Obolo', ['Eastern Obolo I', 'Eastern Obolo II', 'Eastern Obolo III']],
    ['Eket', ['Eket I', 'Eket II', 'Eket III', 'Eket IV', 'Eket V']],
    ['Esit Eket', ['Esit Eket I', 'Esit Eket II', 'Esit Eket III', 'Esit Eket IV']],
    ['Essien Udim', ['Essien Udim I', 'Essien Udim II', 'Essien Udim III', 'Essien Udim IV', 'Essien Udim V']],
    ['Etim Ekpo', ['Etim Ekpo I', 'Etim Ekpo II', 'Etim Ekpo III', 'Etim Ekpo IV']],
    ['Etinan', ['Etinan I', 'Etinan II', 'Etinan III', 'Etinan IV', 'Etinan V']],
    ['Ibeno', ['Ibeno I', 'Ibeno II', 'Ibeno III', 'Ibeno IV']],
    ['Ibesikpo Asutan', ['Ibesikpo Asutan I', 'Ibesikpo Asutan II', 'Ibesikpo Asutan III', 'Ibesikpo Asutan IV']],
    ['Ibiono Ibom', ['Ibiono Ibom I', 'Ibiono Ibom II', 'Ibiono Ibom III', 'Ibiono Ibom IV', 'Ibiono Ibom V']],
    ['Ika', ['Ika I', 'Ika II', 'Ika III', 'Ika IV']],
    ['Ikono', ['Ikono I', 'Ikono II', 'Ikono III', 'Ikono IV', 'Ikono V']],
    ['Ikot Abasi', ['Ikot Abasi I', 'Ikot Abasi II', 'Ikot Abasi III', 'Ikot Abasi IV']],
    ['Ikot Ekpene', ['Ikot Ekpene I', 'Ikot Ekpene II', 'Ikot Ekpene III', 'Ikot Ekpene IV', 'Ikot Ekpene V']],
    ['Ini', ['Ini I', 'Ini II', 'Ini III', 'Ini IV']],
    ['Itu', ['Itu I', 'Itu II', 'Itu III', 'Itu IV', 'Itu V']],
    ['Mbo', ['Mbo I', 'Mbo II', 'Mbo III', 'Mbo IV']],
    ['Mkpat Enin', ['Mkpat Enin I', 'Mkpat Enin II', 'Mkpat Enin III', 'Mkpat Enin IV']],
    ['Nsit Atai', ['Nsit Atai I', 'Nsit Atai II', 'Nsit Atai III', 'Nsit Atai IV']],
    ['Nsit Ibom', ['Nsit Ibom I', 'Nsit Ibom II', 'Nsit Ibom III', 'Nsit Ibom IV']],
    ['Nsit Ubium', ['Nsit Ubium I', 'Nsit Ubium II', 'Nsit Ubium III', 'Nsit Ubium IV']],
    ['Obot Akara', ['Obot Akara I', 'Obot Akara II', 'Obot Akara III', 'Obot Akara IV']],
    ['Okobo', ['Okobo I', 'Okobo II', 'Okobo III', 'Okobo IV']],
    ['Onna', ['Onna I', 'Onna II', 'Onna III', 'Onna IV', 'Onna V']],
    ['Oron', ['Oron I', 'Oron II', 'Oron III', 'Oron IV']],
    ['Oruk Anam', ['Oruk Anam I', 'Oruk Anam II', 'Oruk Anam III', 'Oruk Anam IV', 'Oruk Anam V']],
    ['Udung Uko', ['Udung Uko I', 'Udung Uko II', 'Udung Uko III']],
    ['Ukanafun', ['Ukanafun I', 'Ukanafun II', 'Ukanafun III', 'Ukanafun IV']],
    ['Uruan', ['Uruan I', 'Uruan II', 'Uruan III', 'Uruan IV', 'Uruan V']],
    ['Urue Offong/Oruko', ['Urue Offong I', 'Urue Offong II', 'Urue Offong III']],
    ['Uyo', ['Uyo I', 'Uyo II', 'Uyo III', 'Uyo IV', 'Uyo V', 'Uyo VI']],
  ]),
  makeState('anambra', 'Anambra', [
    ['Aguata', ['Aguata I', 'Aguata II', 'Aguata III', 'Aguata IV', 'Aguata V']],
    ['Anambra East', ['Anambra East I', 'Anambra East II', 'Anambra East III', 'Anambra East IV']],
    ['Anambra West', ['Anambra West I', 'Anambra West II', 'Anambra West III', 'Anambra West IV']],
    ['Anaocha', ['Anaocha I', 'Anaocha II', 'Anaocha III', 'Anaocha IV', 'Anaocha V']],
    ['Awka North', ['Awka North I', 'Awka North II', 'Awka North III', 'Awka North IV']],
    ['Awka South', ['Awka South I', 'Awka South II', 'Awka South III', 'Awka South IV', 'Awka South V']],
    ['Ayamelum', ['Ayamelum I', 'Ayamelum II', 'Ayamelum III', 'Ayamelum IV']],
    ['Dunukofia', ['Dunukofia I', 'Dunukofia II', 'Dunukofia III', 'Dunukofia IV']],
    ['Ekwusigo', ['Ekwusigo I', 'Ekwusigo II', 'Ekwusigo III', 'Ekwusigo IV']],
    ['Idemili North', ['Idemili North I', 'Idemili North II', 'Idemili North III', 'Idemili North IV', 'Idemili North V']],
    ['Idemili South', ['Idemili South I', 'Idemili South II', 'Idemili South III', 'Idemili South IV']],
    ['Ihiala', ['Ihiala I', 'Ihiala II', 'Ihiala III', 'Ihiala IV', 'Ihiala V']],
    ['Njikoka', ['Njikoka I', 'Njikoka II', 'Njikoka III', 'Njikoka IV']],
    ['Nnewi North', ['Nnewi North I', 'Nnewi North II', 'Nnewi North III', 'Nnewi North IV', 'Nnewi North V']],
    ['Nnewi South', ['Nnewi South I', 'Nnewi South II', 'Nnewi South III', 'Nnewi South IV']],
    ['Ogbaru', ['Ogbaru I', 'Ogbaru II', 'Ogbaru III', 'Ogbaru IV', 'Ogbaru V']],
    ['Onitsha North', ['Onitsha North I', 'Onitsha North II', 'Onitsha North III', 'Onitsha North IV']],
    ['Onitsha South', ['Onitsha South I', 'Onitsha South II', 'Onitsha South III', 'Onitsha South IV']],
    ['Orumba North', ['Orumba North I', 'Orumba North II', 'Orumba North III', 'Orumba North IV']],
    ['Orumba South', ['Orumba South I', 'Orumba South II', 'Orumba South III', 'Orumba South IV']],
    ['Oyi', ['Oyi I', 'Oyi II', 'Oyi III', 'Oyi IV']],
  ]),
  makeState('bauchi', 'Bauchi', [
    ['Alkaleri', ['Alkaleri I', 'Alkaleri II', 'Alkaleri III', 'Alkaleri IV', 'Alkaleri V']],
    ['Bauchi', ['Bauchi I', 'Bauchi II', 'Bauchi III', 'Bauchi IV', 'Bauchi V', 'Bauchi VI']],
    ['Bogoro', ['Bogoro I', 'Bogoro II', 'Bogoro III', 'Bogoro IV']],
    ['Damban', ['Damban I', 'Damban II', 'Damban III', 'Damban IV']],
    ['Darazo', ['Darazo I', 'Darazo II', 'Darazo III', 'Darazo IV', 'Darazo V']],
    ['Dass', ['Dass I', 'Dass II', 'Dass III', 'Dass IV']],
    ['Gamawa', ['Gamawa I', 'Gamawa II', 'Gamawa III', 'Gamawa IV', 'Gamawa V']],
    ['Ganjuwa', ['Ganjuwa I', 'Ganjuwa II', 'Ganjuwa III', 'Ganjuwa IV']],
    ['Giade', ['Giade I', 'Giade II', 'Giade III', 'Giade IV']],
    ['Itas/Gadau', ['Itas/Gadau I', 'Itas/Gadau II', 'Itas/Gadau III', 'Itas/Gadau IV']],
    ["Jama'are", ["Jama'are I", "Jama'are II", "Jama'are III", "Jama'are IV"]],
    ['Katagum', ['Katagum I', 'Katagum II', 'Katagum III', 'Katagum IV', 'Katagum V']],
    ['Kirfi', ['Kirfi I', 'Kirfi II', 'Kirfi III', 'Kirfi IV']],
    ['Misau', ['Misau I', 'Misau II', 'Misau III', 'Misau IV', 'Misau V']],
    ['Ningi', ['Ningi I', 'Ningi II', 'Ningi III', 'Ningi IV', 'Ningi V']],
    ['Shira', ['Shira I', 'Shira II', 'Shira III', 'Shira IV']],
    ['Tafawa Balewa', ['Tafawa Balewa I', 'Tafawa Balewa II', 'Tafawa Balewa III', 'Tafawa Balewa IV', 'Tafawa Balewa V']],
    ['Toro', ['Toro I', 'Toro II', 'Toro III', 'Toro IV', 'Toro V']],
    ['Warji', ['Warji I', 'Warji II', 'Warji III', 'Warji IV']],
    ['Zaki', ['Zaki I', 'Zaki II', 'Zaki III', 'Zaki IV', 'Zaki V']],
  ]),
  makeState('bayelsa', 'Bayelsa', [
    ['Brass', ['Brass I', 'Brass II', 'Brass III', 'Brass IV', 'Brass V']],
    ['Ekeremor', ['Ekeremor I', 'Ekeremor II', 'Ekeremor III', 'Ekeremor IV', 'Ekeremor V']],
    ['Kolokuma/Opokuma', ['Kolokuma I', 'Kolokuma II', 'Kolokuma III', 'Opokuma I', 'Opokuma II']],
    ['Nembe', ['Nembe I', 'Nembe II', 'Nembe III', 'Nembe IV', 'Nembe V']],
    ['Ogbia', ['Ogbia I', 'Ogbia II', 'Ogbia III', 'Ogbia IV', 'Ogbia V']],
    ['Sagbama', ['Sagbama I', 'Sagbama II', 'Sagbama III', 'Sagbama IV', 'Sagbama V']],
    ['Southern Ijaw', ['Southern Ijaw I', 'Southern Ijaw II', 'Southern Ijaw III', 'Southern Ijaw IV', 'Southern Ijaw V']],
    ['Yenagoa', ['Yenagoa I', 'Yenagoa II', 'Yenagoa III', 'Yenagoa IV', 'Yenagoa V', 'Yenagoa VI']],
  ]),
  makeState('benue', 'Benue', [
    ['Ado', ['Ado I', 'Ado II', 'Ado III', 'Ado IV', 'Ado V']],
    ['Agatu', ['Agatu I', 'Agatu II', 'Agatu III', 'Agatu IV']],
    ['Apa', ['Apa I', 'Apa II', 'Apa III', 'Apa IV']],
    ['Buruku', ['Buruku I', 'Buruku II', 'Buruku III', 'Buruku IV', 'Buruku V']],
    ['Gboko', ['Gboko I', 'Gboko II', 'Gboko III', 'Gboko IV', 'Gboko V', 'Gboko VI']],
    ['Guma', ['Guma I', 'Guma II', 'Guma III', 'Guma IV', 'Guma V']],
    ['Gwer East', ['Gwer East I', 'Gwer East II', 'Gwer East III', 'Gwer East IV']],
    ['Gwer West', ['Gwer West I', 'Gwer West II', 'Gwer West III', 'Gwer West IV']],
    ['Katsina-Ala', ['Katsina-Ala I', 'Katsina-Ala II', 'Katsina-Ala III', 'Katsina-Ala IV', 'Katsina-Ala V']],
    ['Konshisha', ['Konshisha I', 'Konshisha II', 'Konshisha III', 'Konshisha IV', 'Konshisha V']],
    ['Kwande', ['Kwande I', 'Kwande II', 'Kwande III', 'Kwande IV', 'Kwande V']],
    ['Logo', ['Logo I', 'Logo II', 'Logo III', 'Logo IV']],
    ['Makurdi', ['Makurdi I', 'Makurdi II', 'Makurdi III', 'Makurdi IV', 'Makurdi V', 'Makurdi VI']],
    ['Obi', ['Obi I', 'Obi II', 'Obi III', 'Obi IV']],
    ['Ogbadibo', ['Ogbadibo I', 'Ogbadibo II', 'Ogbadibo III', 'Ogbadibo IV']],
    ['Ohimini', ['Ohimini I', 'Ohimini II', 'Ohimini III', 'Ohimini IV']],
    ['Oju', ['Oju I', 'Oju II', 'Oju III', 'Oju IV', 'Oju V']],
    ['Okpokwu', ['Okpokwu I', 'Okpokwu II', 'Okpokwu III', 'Okpokwu IV', 'Okpokwu V']],
    ['Otukpo', ['Otukpo I', 'Otukpo II', 'Otukpo III', 'Otukpo IV', 'Otukpo V']],
    ['Tarka', ['Tarka I', 'Tarka II', 'Tarka III', 'Tarka IV']],
    ['Ukum', ['Ukum I', 'Ukum II', 'Ukum III', 'Ukum IV', 'Ukum V']],
    ['Ushongo', ['Ushongo I', 'Ushongo II', 'Ushongo III', 'Ushongo IV', 'Ushongo V']],
    ['Vandeikya', ['Vandeikya I', 'Vandeikya II', 'Vandeikya III', 'Vandeikya IV', 'Vandeikya V']],
  ]),
  makeState('borno', 'Borno', [
    ['Abadam', ['Abadam I', 'Abadam II', 'Abadam III']],
    ['Askira/Uba', ['Askira I', 'Askira II', 'Askira III', 'Uba I', 'Uba II']],
    ['Bama', ['Bama I', 'Bama II', 'Bama III', 'Bama IV', 'Bama V']],
    ['Bayo', ['Bayo I', 'Bayo II', 'Bayo III']],
    ['Biu', ['Biu I', 'Biu II', 'Biu III', 'Biu IV', 'Biu V']],
    ['Chibok', ['Chibok I', 'Chibok II', 'Chibok III', 'Chibok IV']],
    ['Damboa', ['Damboa I', 'Damboa II', 'Damboa III', 'Damboa IV']],
    ['Dikwa', ['Dikwa I', 'Dikwa II', 'Dikwa III', 'Dikwa IV']],
    ['Gubio', ['Gubio I', 'Gubio II', 'Gubio III', 'Gubio IV']],
    ['Guzamala', ['Guzamala I', 'Guzamala II', 'Guzamala III']],
    ['Gwoza', ['Gwoza I', 'Gwoza II', 'Gwoza III', 'Gwoza IV', 'Gwoza V']],
    ['Hawul', ['Hawul I', 'Hawul II', 'Hawul III', 'Hawul IV']],
    ['Jere', ['Jere I', 'Jere II', 'Jere III', 'Jere IV', 'Jere V']],
    ['Kaga', ['Kaga I', 'Kaga II', 'Kaga III', 'Kaga IV']],
    ['Kala/Balge', ['Kala I', 'Kala II', 'Balge I', 'Balge II']],
    ['Konduga', ['Konduga I', 'Konduga II', 'Konduga III', 'Konduga IV']],
    ['Kukawa', ['Kukawa I', 'Kukawa II', 'Kukawa III', 'Kukawa IV']],
    ['Kwaya Kusar', ['Kwaya Kusar I', 'Kwaya Kusar II', 'Kwaya Kusar III']],
    ['Mafa', ['Mafa I', 'Mafa II', 'Mafa III', 'Mafa IV']],
    ['Magumeri', ['Magumeri I', 'Magumeri II', 'Magumeri III', 'Magumeri IV']],
    ['Maiduguri', ['Maiduguri I', 'Maiduguri II', 'Maiduguri III', 'Maiduguri IV', 'Maiduguri V', 'Maiduguri VI']],
    ['Marte', ['Marte I', 'Marte II', 'Marte III']],
    ['Mobbar', ['Mobbar I', 'Mobbar II', 'Mobbar III', 'Mobbar IV']],
    ['Monguno', ['Monguno I', 'Monguno II', 'Monguno III', 'Monguno IV']],
    ['Ngala', ['Ngala I', 'Ngala II', 'Ngala III', 'Ngala IV']],
    ['Nganzai', ['Nganzai I', 'Nganzai II', 'Nganzai III']],
    ['Shani', ['Shani I', 'Shani II', 'Shani III', 'Shani IV']],
  ]),
  makeState('cross-river', 'Cross River', [
    ['Abi', ['Abi I', 'Abi II', 'Abi III', 'Abi IV', 'Abi V']],
    ['Akamkpa', ['Akamkpa I', 'Akamkpa II', 'Akamkpa III', 'Akamkpa IV', 'Akamkpa V']],
    ['Akpabuyo', ['Akpabuyo I', 'Akpabuyo II', 'Akpabuyo III', 'Akpabuyo IV']],
    ['Bakassi', ['Bakassi I', 'Bakassi II', 'Bakassi III']],
    ['Bekwarra', ['Bekwarra I', 'Bekwarra II', 'Bekwarra III', 'Bekwarra IV']],
    ['Biase', ['Biase I', 'Biase II', 'Biase III', 'Biase IV', 'Biase V']],
    ['Boki', ['Boki I', 'Boki II', 'Boki III', 'Boki IV', 'Boki V']],
    ['Calabar Municipal', ['Calabar Municipal I', 'Calabar Municipal II', 'Calabar Municipal III', 'Calabar Municipal IV', 'Calabar Municipal V']],
    ['Calabar South', ['Calabar South I', 'Calabar South II', 'Calabar South III', 'Calabar South IV', 'Calabar South V']],
    ['Etung', ['Etung I', 'Etung II', 'Etung III', 'Etung IV']],
    ['Ikom', ['Ikom I', 'Ikom II', 'Ikom III', 'Ikom IV', 'Ikom V']],
    ['Obanliku', ['Obanliku I', 'Obanliku II', 'Obanliku III', 'Obanliku IV']],
    ['Obubra', ['Obubra I', 'Obubra II', 'Obubra III', 'Obubra IV', 'Obubra V']],
    ['Obudu', ['Obudu I', 'Obudu II', 'Obudu III', 'Obudu IV', 'Obudu V']],
    ['Odukpani', ['Odukpani I', 'Odukpani II', 'Odukpani III', 'Odukpani IV']],
    ['Ogoja', ['Ogoja I', 'Ogoja II', 'Ogoja III', 'Ogoja IV', 'Ogoja V']],
    ['Yakuur', ['Yakuur I', 'Yakuur II', 'Yakuur III', 'Yakuur IV']],
    ['Yala', ['Yala I', 'Yala II', 'Yala III', 'Yala IV', 'Yala V']],
  ]),
  makeState('delta', 'Delta', [
    ['Aniocha North', ['Aniocha North I', 'Aniocha North II', 'Aniocha North III', 'Aniocha North IV', 'Aniocha North V']],
    ['Aniocha South', ['Aniocha South I', 'Aniocha South II', 'Aniocha South III', 'Aniocha South IV']],
    ['Bomadi', ['Bomadi I', 'Bomadi II', 'Bomadi III', 'Bomadi IV']],
    ['Burutu', ['Burutu I', 'Burutu II', 'Burutu III', 'Burutu IV', 'Burutu V']],
    ['Ethiope East', ['Ethiope East I', 'Ethiope East II', 'Ethiope East III', 'Ethiope East IV']],
    ['Ethiope West', ['Ethiope West I', 'Ethiope West II', 'Ethiope West III', 'Ethiope West IV']],
    ['Ika North East', ['Ika North East I', 'Ika North East II', 'Ika North East III', 'Ika North East IV']],
    ['Ika South', ['Ika South I', 'Ika South II', 'Ika South III', 'Ika South IV']],
    ['Isoko North', ['Isoko North I', 'Isoko North II', 'Isoko North III', 'Isoko North IV', 'Isoko North V']],
    ['Isoko South', ['Isoko South I', 'Isoko South II', 'Isoko South III', 'Isoko South IV', 'Isoko South V']],
    ['Ndokwa East', ['Ndokwa East I', 'Ndokwa East II', 'Ndokwa East III', 'Ndokwa East IV']],
    ['Ndokwa West', ['Ndokwa West I', 'Ndokwa West II', 'Ndokwa West III', 'Ndokwa West IV']],
    ['Okpe', ['Okpe I', 'Okpe II', 'Okpe III', 'Okpe IV']],
    ['Oshimili North', ['Oshimili North I', 'Oshimili North II', 'Oshimili North III', 'Oshimili North IV']],
    ['Oshimili South', ['Oshimili South I', 'Oshimili South II', 'Oshimili South III', 'Oshimili South IV', 'Oshimili South V']],
    ['Patani', ['Patani I', 'Patani II', 'Patani III', 'Patani IV']],
    ['Sapele', ['Sapele I', 'Sapele II', 'Sapele III', 'Sapele IV', 'Sapele V']],
    ['Udu', ['Udu I', 'Udu II', 'Udu III', 'Udu IV']],
    ['Ughelli North', ['Ughelli North I', 'Ughelli North II', 'Ughelli North III', 'Ughelli North IV', 'Ughelli North V']],
    ['Ughelli South', ['Ughelli South I', 'Ughelli South II', 'Ughelli South III', 'Ughelli South IV']],
    ['Ukwuani', ['Ukwuani I', 'Ukwuani II', 'Ukwuani III', 'Ukwuani IV']],
    ['Uvwie', ['Uvwie I', 'Uvwie II', 'Uvwie III', 'Uvwie IV', 'Uvwie V']],
    ['Warri North', ['Warri North I', 'Warri North II', 'Warri North III', 'Warri North IV']],
    ['Warri South', ['Warri South I', 'Warri South II', 'Warri South III', 'Warri South IV', 'Warri South V']],
    ['Warri South West', ['Warri South West I', 'Warri South West II', 'Warri South West III', 'Warri South West IV']],
  ]),
  makeState('ebonyi', 'Ebonyi', [
    ['Abakaliki', ['Abakaliki I', 'Abakaliki II', 'Abakaliki III', 'Abakaliki IV', 'Abakaliki V']],
    ['Afikpo North', ['Afikpo North I', 'Afikpo North II', 'Afikpo North III', 'Afikpo North IV', 'Afikpo North V']],
    ['Afikpo South', ['Afikpo South I', 'Afikpo South II', 'Afikpo South III', 'Afikpo South IV']],
    ['Ebonyi', ['Ebonyi I', 'Ebonyi II', 'Ebonyi III', 'Ebonyi IV']],
    ['Ezza North', ['Ezza North I', 'Ezza North II', 'Ezza North III', 'Ezza North IV', 'Ezza North V']],
    ['Ezza South', ['Ezza South I', 'Ezza South II', 'Ezza South III', 'Ezza South IV']],
    ['Ikwo', ['Ikwo I', 'Ikwo II', 'Ikwo III', 'Ikwo IV', 'Ikwo V']],
    ['Ishielu', ['Ishielu I', 'Ishielu II', 'Ishielu III', 'Ishielu IV', 'Ishielu V']],
    ['Ivo', ['Ivo I', 'Ivo II', 'Ivo III', 'Ivo IV']],
    ['Izzi', ['Izzi I', 'Izzi II', 'Izzi III', 'Izzi IV', 'Izzi V']],
    ['Ohaozara', ['Ohaozara I', 'Ohaozara II', 'Ohaozara III', 'Ohaozara IV', 'Ohaozara V']],
    ['Ohaukwu', ['Ohaukwu I', 'Ohaukwu II', 'Ohaukwu III', 'Ohaukwu IV', 'Ohaukwu V']],
    ['Onicha', ['Onicha I', 'Onicha II', 'Onicha III', 'Onicha IV']],
  ]),
  makeState('edo', 'Edo', [
    ['Akoko-Edo', ['Akoko-Edo I', 'Akoko-Edo II', 'Akoko-Edo III', 'Akoko-Edo IV', 'Akoko-Edo V']],
    ['Egor', ['Egor I', 'Egor II', 'Egor III', 'Egor IV', 'Egor V']],
    ['Esan Central', ['Esan Central I', 'Esan Central II', 'Esan Central III', 'Esan Central IV']],
    ['Esan North East', ['Esan North East I', 'Esan North East II', 'Esan North East III', 'Esan North East IV']],
    ['Esan South East', ['Esan South East I', 'Esan South East II', 'Esan South East III', 'Esan South East IV']],
    ['Esan West', ['Esan West I', 'Esan West II', 'Esan West III', 'Esan West IV', 'Esan West V']],
    ['Etsako Central', ['Etsako Central I', 'Etsako Central II', 'Etsako Central III', 'Etsako Central IV']],
    ['Etsako East', ['Etsako East I', 'Etsako East II', 'Etsako East III', 'Etsako East IV', 'Etsako East V']],
    ['Etsako West', ['Etsako West I', 'Etsako West II', 'Etsako West III', 'Etsako West IV', 'Etsako West V']],
    ['Igueben', ['Igueben I', 'Igueben II', 'Igueben III', 'Igueben IV']],
    ['Ikpoba Okha', ['Ikpoba Okha I', 'Ikpoba Okha II', 'Ikpoba Okha III', 'Ikpoba Okha IV', 'Ikpoba Okha V']],
    ['Orhionmwon', ['Orhionmwon I', 'Orhionmwon II', 'Orhionmwon III', 'Orhionmwon IV', 'Orhionmwon V']],
    ['Oredo', ['Oredo I', 'Oredo II', 'Oredo III', 'Oredo IV', 'Oredo V', 'Oredo VI']],
    ['Ovia North East', ['Ovia North East I', 'Ovia North East II', 'Ovia North East III', 'Ovia North East IV', 'Ovia North East V']],
    ['Ovia South West', ['Ovia South West I', 'Ovia South West II', 'Ovia South West III', 'Ovia South West IV']],
    ['Owan East', ['Owan East I', 'Owan East II', 'Owan East III', 'Owan East IV', 'Owan East V']],
    ['Owan West', ['Owan West I', 'Owan West II', 'Owan West III', 'Owan West IV']],
    ['Uhunmwonde', ['Uhunmwonde I', 'Uhunmwonde II', 'Uhunmwonde III', 'Uhunmwonde IV', 'Uhunmwonde V']],
  ]),
  makeState('ekiti', 'Ekiti', [
    ['Ado Ekiti', ['Ado Ekiti I', 'Ado Ekiti II', 'Ado Ekiti III', 'Ado Ekiti IV', 'Ado Ekiti V']],
    ['Efon', ['Efon I', 'Efon II', 'Efon III', 'Efon IV']],
    ['Ekiti East', ['Ekiti East I', 'Ekiti East II', 'Ekiti East III', 'Ekiti East IV']],
    ['Ekiti South West', ['Ekiti South West I', 'Ekiti South West II', 'Ekiti South West III', 'Ekiti South West IV']],
    ['Ekiti West', ['Ekiti West I', 'Ekiti West II', 'Ekiti West III', 'Ekiti West IV']],
    ['Emure', ['Emure I', 'Emure II', 'Emure III', 'Emure IV']],
    ['Gbonyin', ['Gbonyin I', 'Gbonyin II', 'Gbonyin III', 'Gbonyin IV', 'Gbonyin V']],
    ['Ido Osi', ['Ido Osi I', 'Ido Osi II', 'Ido Osi III', 'Ido Osi IV']],
    ['Ijero', ['Ijero I', 'Ijero II', 'Ijero III', 'Ijero IV', 'Ijero V']],
    ['Ikere', ['Ikere I', 'Ikere II', 'Ikere III', 'Ikere IV', 'Ikere V']],
    ['Ikole', ['Ikole I', 'Ikole II', 'Ikole III', 'Ikole IV', 'Ikole V']],
    ['Ilejemeje', ['Ilejemeje I', 'Ilejemeje II', 'Ilejemeje III', 'Ilejemeje IV']],
    ['Irepodun/Ifelodun', ['Irepodun I', 'Irepodun II', 'Irepodun III', 'Irepodun IV', 'Irepodun V']],
    ['Ise/Orun', ['Ise I', 'Ise II', 'Ise III', 'Orun I', 'Orun II']],
    ['Moba', ['Moba I', 'Moba II', 'Moba III', 'Moba IV', 'Moba V']],
    ['Oye', ['Oye I', 'Oye II', 'Oye III', 'Oye IV', 'Oye V']],
  ]),
  makeState('enugu', 'Enugu', [
    ['Aninri', ['Aninri I', 'Aninri II', 'Aninri III', 'Aninri IV', 'Aninri V']],
    ['Awgu', ['Awgu I', 'Awgu II', 'Awgu III', 'Awgu IV', 'Awgu V']],
    ['Enugu East', ['Enugu East I', 'Enugu East II', 'Enugu East III', 'Enugu East IV', 'Enugu East V']],
    ['Enugu North', ['Enugu North I', 'Enugu North II', 'Enugu North III', 'Enugu North IV', 'Enugu North V']],
    ['Enugu South', ['Enugu South I', 'Enugu South II', 'Enugu South III', 'Enugu South IV']],
    ['Ezeagu', ['Ezeagu I', 'Ezeagu II', 'Ezeagu III', 'Ezeagu IV', 'Ezeagu V']],
    ['Igbo Etiti', ['Igbo Etiti I', 'Igbo Etiti II', 'Igbo Etiti III', 'Igbo Etiti IV', 'Igbo Etiti V']],
    ['Igbo Eze North', ['Igbo Eze North I', 'Igbo Eze North II', 'Igbo Eze North III', 'Igbo Eze North IV', 'Igbo Eze North V']],
    ['Igbo Eze South', ['Igbo Eze South I', 'Igbo Eze South II', 'Igbo Eze South III', 'Igbo Eze South IV']],
    ['Isi Uzo', ['Isi Uzo I', 'Isi Uzo II', 'Isi Uzo III', 'Isi Uzo IV', 'Isi Uzo V']],
    ['Nkanu East', ['Nkanu East I', 'Nkanu East II', 'Nkanu East III', 'Nkanu East IV']],
    ['Nkanu West', ['Nkanu West I', 'Nkanu West II', 'Nkanu West III', 'Nkanu West IV', 'Nkanu West V']],
    ['Nsukka', ['Nsukka I', 'Nsukka II', 'Nsukka III', 'Nsukka IV', 'Nsukka V', 'Nsukka VI']],
    ['Oji River', ['Oji River I', 'Oji River II', 'Oji River III', 'Oji River IV']],
    ['Udenu', ['Udenu I', 'Udenu II', 'Udenu III', 'Udenu IV', 'Udenu V']],
    ['Udi', ['Udi I', 'Udi II', 'Udi III', 'Udi IV', 'Udi V']],
    ['Uzo Uwani', ['Uzo Uwani I', 'Uzo Uwani II', 'Uzo Uwani III', 'Uzo Uwani IV', 'Uzo Uwani V']],
  ]),
  makeState('fct', 'Federal Capital Territory', [
    ['Abaji', ['Abaji I', 'Abaji II', 'Abaji III', 'Abaji IV', 'Abaji V']],
    ['Bwari', ['Bwari Central', 'Ushafa', 'Dutse', 'Igu', 'Kawu', 'Shere']],
    ['Gwagwalada', ['Gwagwalada Central', 'Dobi', 'Ikwa', 'Zuba', 'Paiko', 'Tungan Maje']],
    ['Kuje', ['Kuje I', 'Kuje II', 'Kuje III', 'Kuje IV', 'Kuje V']],
    ['Kwali', ['Kwali I', 'Kwali II', 'Kwali III', 'Kwali IV', 'Kwali V']],
    ['Municipal Area Council', ['Garki', 'Wuse', 'Maitama', 'Asokoro', 'Gwarinpa', 'Kubwa', 'Karu', 'Nyanya', 'Lugbe', 'Gwagwa']],
  ]),
  makeState('gombe', 'Gombe', [
    ['Akko', ['Akko I', 'Akko II', 'Akko III', 'Akko IV', 'Akko V']],
    ['Balanga', ['Balanga I', 'Balanga II', 'Balanga III', 'Balanga IV']],
    ['Billiri', ['Billiri I', 'Billiri II', 'Billiri III', 'Billiri IV']],
    ['Dukku', ['Dukku I', 'Dukku II', 'Dukku III', 'Dukku IV', 'Dukku V']],
    ['Funakaye', ['Funakaye I', 'Funakaye II', 'Funakaye III', 'Funakaye IV']],
    ['Gombe', ['Gombe I', 'Gombe II', 'Gombe III', 'Gombe IV', 'Gombe V', 'Gombe VI']],
    ['Kaltungo', ['Kaltungo I', 'Kaltungo II', 'Kaltungo III', 'Kaltungo IV']],
    ['Kwami', ['Kwami I', 'Kwami II', 'Kwami III', 'Kwami IV']],
    ['Nafada', ['Nafada I', 'Nafada II', 'Nafada III', 'Nafada IV']],
    ['Shomgom', ['Shomgom I', 'Shomgom II', 'Shomgom III', 'Shomgom IV']],
    ['Yamaltu/Deba', ['Yamaltu I', 'Yamaltu II', 'Yamaltu III', 'Deba I', 'Deba II']],
  ]),
  makeState('imo', 'Imo', [
    ['Aboh Mbaise', ['Aboh Mbaise I', 'Aboh Mbaise II', 'Aboh Mbaise III', 'Aboh Mbaise IV', 'Aboh Mbaise V']],
    ['Ahiazu Mbaise', ['Ahiazu Mbaise I', 'Ahiazu Mbaise II', 'Ahiazu Mbaise III', 'Ahiazu Mbaise IV']],
    ['Ehime Mbano', ['Ehime Mbano I', 'Ehime Mbano II', 'Ehime Mbano III', 'Ehime Mbano IV', 'Ehime Mbano V']],
    ['Ezinihitte', ['Ezinihitte I', 'Ezinihitte II', 'Ezinihitte III', 'Ezinihitte IV']],
    ['Ideato North', ['Ideato North I', 'Ideato North II', 'Ideato North III', 'Ideato North IV']],
    ['Ideato South', ['Ideato South I', 'Ideato South II', 'Ideato South III', 'Ideato South IV']],
    ['Ihitte/Uboma', ['Ihitte I', 'Ihitte II', 'Ihitte III', 'Uboma I', 'Uboma II']],
    ['Ikeduru', ['Ikeduru I', 'Ikeduru II', 'Ikeduru III', 'Ikeduru IV', 'Ikeduru V']],
    ['Isiala Mbano', ['Isiala Mbano I', 'Isiala Mbano II', 'Isiala Mbano III', 'Isiala Mbano IV', 'Isiala Mbano V']],
    ['Isu', ['Isu I', 'Isu II', 'Isu III', 'Isu IV']],
    ['Mbaitoli', ['Mbaitoli I', 'Mbaitoli II', 'Mbaitoli III', 'Mbaitoli IV', 'Mbaitoli V']],
    ['Ngor Okpala', ['Ngor Okpala I', 'Ngor Okpala II', 'Ngor Okpala III', 'Ngor Okpala IV']],
    ['Njaba', ['Njaba I', 'Njaba II', 'Njaba III', 'Njaba IV']],
    ['Nkwerre', ['Nkwerre I', 'Nkwerre II', 'Nkwerre III', 'Nkwerre IV']],
    ['Nwangele', ['Nwangele I', 'Nwangele II', 'Nwangele III', 'Nwangele IV']],
    ['Obowo', ['Obowo I', 'Obowo II', 'Obowo III', 'Obowo IV', 'Obowo V']],
    ['Oguta', ['Oguta I', 'Oguta II', 'Oguta III', 'Oguta IV', 'Oguta V']],
    ['Ohaji/Egbema', ['Ohaji I', 'Ohaji II', 'Ohaji III', 'Egbema I', 'Egbema II']],
    ['Okigwe', ['Okigwe I', 'Okigwe II', 'Okigwe III', 'Okigwe IV', 'Okigwe V']],
    ['Orlu', ['Orlu I', 'Orlu II', 'Orlu III', 'Orlu IV', 'Orlu V']],
    ['Orsu', ['Orsu I', 'Orsu II', 'Orsu III', 'Orsu IV']],
    ['Oru East', ['Oru East I', 'Oru East II', 'Oru East III', 'Oru East IV']],
    ['Oru West', ['Oru West I', 'Oru West II', 'Oru West III', 'Oru West IV']],
    ['Owerri Municipal', ['Owerri Municipal I', 'Owerri Municipal II', 'Owerri Municipal III', 'Owerri Municipal IV', 'Owerri Municipal V']],
    ['Owerri North', ['Owerri North I', 'Owerri North II', 'Owerri North III', 'Owerri North IV']],
    ['Owerri West', ['Owerri West I', 'Owerri West II', 'Owerri West III', 'Owerri West IV', 'Owerri West V']],
    ['Unuimo', ['Unuimo I', 'Unuimo II', 'Unuimo III', 'Unuimo IV']],
  ]),
  makeState('jigawa', 'Jigawa', [
    ['Auyo', ['Auyo I', 'Auyo II', 'Auyo III', 'Auyo IV']],
    ['Babura', ['Babura I', 'Babura II', 'Babura III', 'Babura IV', 'Babura V']],
    ['Biriniwa', ['Biriniwa I', 'Biriniwa II', 'Biriniwa III', 'Biriniwa IV']],
    ['Birnin Kudu', ['Birnin Kudu I', 'Birnin Kudu II', 'Birnin Kudu III', 'Birnin Kudu IV', 'Birnin Kudu V']],
    ['Buji', ['Buji I', 'Buji II', 'Buji III', 'Buji IV']],
    ['Dutse', ['Dutse I', 'Dutse II', 'Dutse III', 'Dutse IV', 'Dutse V']],
    ['Gagarawa', ['Gagarawa I', 'Gagarawa II', 'Gagarawa III', 'Gagarawa IV']],
    ['Garki', ['Garki I', 'Garki II', 'Garki III', 'Garki IV']],
    ['Gumel', ['Gumel I', 'Gumel II', 'Gumel III', 'Gumel IV', 'Gumel V']],
    ['Guri', ['Guri I', 'Guri II', 'Guri III', 'Guri IV']],
    ['Gwaram', ['Gwaram I', 'Gwaram II', 'Gwaram III', 'Gwaram IV', 'Gwaram V']],
    ['Gwiwa', ['Gwiwa I', 'Gwiwa II', 'Gwiwa III', 'Gwiwa IV']],
    ['Hadejia', ['Hadejia I', 'Hadejia II', 'Hadejia III', 'Hadejia IV', 'Hadejia V']],
    ['Jahun', ['Jahun I', 'Jahun II', 'Jahun III', 'Jahun IV', 'Jahun V']],
    ['Kafin Hausa', ['Kafin Hausa I', 'Kafin Hausa II', 'Kafin Hausa III', 'Kafin Hausa IV']],
    ['Kaugama', ['Kaugama I', 'Kaugama II', 'Kaugama III', 'Kaugama IV']],
    ['Kazaure', ['Kazaure I', 'Kazaure II', 'Kazaure III', 'Kazaure IV', 'Kazaure V']],
    ['Kiri Kasama', ['Kiri Kasama I', 'Kiri Kasama II', 'Kiri Kasama III', 'Kiri Kasama IV']],
    ['Kiyawa', ['Kiyawa I', 'Kiyawa II', 'Kiyawa III', 'Kiyawa IV']],
    ['Maigatari', ['Maigatari I', 'Maigatari II', 'Maigatari III', 'Maigatari IV', 'Maigatari V']],
    ['Malam Madori', ['Malam Madori I', 'Malam Madori II', 'Malam Madori III', 'Malam Madori IV']],
    ['Miga', ['Miga I', 'Miga II', 'Miga III', 'Miga IV']],
    ['Ringim', ['Ringim I', 'Ringim II', 'Ringim III', 'Ringim IV', 'Ringim V']],
    ['Roni', ['Roni I', 'Roni II', 'Roni III', 'Roni IV']],
    ['Sule Tankarkar', ['Sule Tankarkar I', 'Sule Tankarkar II', 'Sule Tankarkar III', 'Sule Tankarkar IV']],
    ['Taura', ['Taura I', 'Taura II', 'Taura III', 'Taura IV', 'Taura V']],
    ['Yankwashi', ['Yankwashi I', 'Yankwashi II', 'Yankwashi III', 'Yankwashi IV']],
  ]),
  makeState('kaduna', 'Kaduna', [
    ['Birnin Gwari', ['Birnin Gwari I', 'Birnin Gwari II', 'Birnin Gwari III', 'Birnin Gwari IV', 'Birnin Gwari V']],
    ['Chikun', ['Chikun I', 'Chikun II', 'Chikun III', 'Chikun IV', 'Chikun V']],
    ['Giwa', ['Giwa I', 'Giwa II', 'Giwa III', 'Giwa IV']],
    ['Igabi', ['Igabi I', 'Igabi II', 'Igabi III', 'Igabi IV', 'Igabi V']],
    ['Ikara', ['Ikara I', 'Ikara II', 'Ikara III', 'Ikara IV']],
    ['Jaba', ['Jaba I', 'Jaba II', 'Jaba III', 'Jaba IV']],
    ["Jema'a", ["Jema'a I", "Jema'a II", "Jema'a III", "Jema'a IV", "Jema'a V"]],
    ['Kachia', ['Kachia I', 'Kachia II', 'Kachia III', 'Kachia IV', 'Kachia V']],
    ['Kaduna North', ['Kaduna North I', 'Kaduna North II', 'Kaduna North III', 'Kaduna North IV', 'Kaduna North V']],
    ['Kaduna South', ['Kaduna South I', 'Kaduna South II', 'Kaduna South III', 'Kaduna South IV', 'Kaduna South V']],
    ['Kagarko', ['Kagarko I', 'Kagarko II', 'Kagarko III', 'Kagarko IV']],
    ['Kajuru', ['Kajuru I', 'Kajuru II', 'Kajuru III', 'Kajuru IV', 'Kajuru V']],
    ['Kaura', ['Kaura I', 'Kaura II', 'Kaura III', 'Kaura IV', 'Kaura V']],
    ['Kauru', ['Kauru I', 'Kauru II', 'Kauru III', 'Kauru IV']],
    ['Kubau', ['Kubau I', 'Kubau II', 'Kubau III', 'Kubau IV', 'Kubau V']],
    ['Kudan', ['Kudan I', 'Kudan II', 'Kudan III', 'Kudan IV']],
    ['Lere', ['Lere I', 'Lere II', 'Lere III', 'Lere IV', 'Lere V']],
    ['Makarfi', ['Makarfi I', 'Makarfi II', 'Makarfi III', 'Makarfi IV']],
    ['Sabon Gari', ['Sabon Gari I', 'Sabon Gari II', 'Sabon Gari III', 'Sabon Gari IV', 'Sabon Gari V']],
    ['Sanga', ['Sanga I', 'Sanga II', 'Sanga III', 'Sanga IV', 'Sanga V']],
    ['Soba', ['Soba I', 'Soba II', 'Soba III', 'Soba IV', 'Soba V']],
    ['Zangon Kataf', ['Zangon Kataf I', 'Zangon Kataf II', 'Zangon Kataf III', 'Zangon Kataf IV', 'Zangon Kataf V']],
    ['Zaria', ['Zaria I', 'Zaria II', 'Zaria III', 'Zaria IV', 'Zaria V', 'Zaria VI']],
  ]),
  makeState('kano', 'Kano', [
    ['Ajingi', ['Ajingi I', 'Ajingi II', 'Ajingi III', 'Ajingi IV']],
    ['Albasu', ['Albasu I', 'Albasu II', 'Albasu III', 'Albasu IV']],
    ['Bagwai', ['Bagwai I', 'Bagwai II', 'Bagwai III', 'Bagwai IV']],
    ['Bebeji', ['Bebeji I', 'Bebeji II', 'Bebeji III', 'Bebeji IV']],
    ['Bichi', ['Bichi I', 'Bichi II', 'Bichi III', 'Bichi IV', 'Bichi V']],
    ['Bunkure', ['Bunkure I', 'Bunkure II', 'Bunkure III', 'Bunkure IV']],
    ['Dala', ['Dala I', 'Dala II', 'Dala III', 'Dala IV', 'Dala V']],
    ['Dambatta', ['Dambatta I', 'Dambatta II', 'Dambatta III', 'Dambatta IV', 'Dambatta V']],
    ['Dawakin Kudu', ['Dawakin Kudu I', 'Dawakin Kudu II', 'Dawakin Kudu III', 'Dawakin Kudu IV']],
    ['Dawakin Tofa', ['Dawakin Tofa I', 'Dawakin Tofa II', 'Dawakin Tofa III', 'Dawakin Tofa IV']],
    ['Doguwa', ['Doguwa I', 'Doguwa II', 'Doguwa III', 'Doguwa IV']],
    ['Fagge', ['Fagge I', 'Fagge II', 'Fagge III', 'Fagge IV', 'Fagge V']],
    ['Gabasawa', ['Gabasawa I', 'Gabasawa II', 'Gabasawa III', 'Gabasawa IV']],
    ['Garko', ['Garko I', 'Garko II', 'Garko III', 'Garko IV']],
    ['Garun Mallam', ['Garun Mallam I', 'Garun Mallam II', 'Garun Mallam III', 'Garun Mallam IV']],
    ['Gaya', ['Gaya I', 'Gaya II', 'Gaya III', 'Gaya IV', 'Gaya V']],
    ['Gezawa', ['Gezawa I', 'Gezawa II', 'Gezawa III', 'Gezawa IV']],
    ['Gwale', ['Gwale I', 'Gwale II', 'Gwale III', 'Gwale IV', 'Gwale V']],
    ['Gwarzo', ['Gwarzo I', 'Gwarzo II', 'Gwarzo III', 'Gwarzo IV']],
    ['Kabo', ['Kabo I', 'Kabo II', 'Kabo III', 'Kabo IV']],
    ['Kano Municipal', ['Kano Municipal I', 'Kano Municipal II', 'Kano Municipal III', 'Kano Municipal IV', 'Kano Municipal V']],
    ['Karaye', ['Karaye I', 'Karaye II', 'Karaye III', 'Karaye IV']],
    ['Kibiya', ['Kibiya I', 'Kibiya II', 'Kibiya III', 'Kibiya IV']],
    ['Kiru', ['Kiru I', 'Kiru II', 'Kiru III', 'Kiru IV', 'Kiru V']],
    ['Kumbotso', ['Kumbotso I', 'Kumbotso II', 'Kumbotso III', 'Kumbotso IV', 'Kumbotso V']],
    ['Kunchi', ['Kunchi I', 'Kunchi II', 'Kunchi III', 'Kunchi IV']],
    ['Kura', ['Kura I', 'Kura II', 'Kura III', 'Kura IV']],
    ['Madobi', ['Madobi I', 'Madobi II', 'Madobi III', 'Madobi IV']],
    ['Makoda', ['Makoda I', 'Makoda II', 'Makoda III', 'Makoda IV']],
    ['Minjibir', ['Minjibir I', 'Minjibir II', 'Minjibir III', 'Minjibir IV']],
    ['Nasarawa', ['Nasarawa I', 'Nasarawa II', 'Nasarawa III', 'Nasarawa IV', 'Nasarawa V']],
    ['Rano', ['Rano I', 'Rano II', 'Rano III', 'Rano IV']],
    ['Rimin Gado', ['Rimin Gado I', 'Rimin Gado II', 'Rimin Gado III', 'Rimin Gado IV']],
    ['Rogo', ['Rogo I', 'Rogo II', 'Rogo III', 'Rogo IV']],
    ['Shanono', ['Shanono I', 'Shanono II', 'Shanono III', 'Shanono IV']],
    ['Sumaila', ['Sumaila I', 'Sumaila II', 'Sumaila III', 'Sumaila IV', 'Sumaila V']],
    ['Takai', ['Takai I', 'Takai II', 'Takai III', 'Takai IV']],
    ['Tarauni', ['Tarauni I', 'Tarauni II', 'Tarauni III', 'Tarauni IV']],
    ['Tofa', ['Tofa I', 'Tofa II', 'Tofa III', 'Tofa IV']],
    ['Tsanyawa', ['Tsanyawa I', 'Tsanyawa II', 'Tsanyawa III', 'Tsanyawa IV']],
    ['Tudun Wada', ['Tudun Wada I', 'Tudun Wada II', 'Tudun Wada III', 'Tudun Wada IV', 'Tudun Wada V']],
    ['Ungogo', ['Ungogo I', 'Ungogo II', 'Ungogo III', 'Ungogo IV', 'Ungogo V']],
    ['Warawa', ['Warawa I', 'Warawa II', 'Warawa III', 'Warawa IV']],
    ['Wudil', ['Wudil I', 'Wudil II', 'Wudil III', 'Wudil IV', 'Wudil V']],
  ]),
  makeState('katsina', 'Katsina', [
    ['Bakori', ['Bakori I', 'Bakori II', 'Bakori III', 'Bakori IV', 'Bakori V']],
    ['Batagarawa', ['Batagarawa I', 'Batagarawa II', 'Batagarawa III', 'Batagarawa IV']],
    ['Batsari', ['Batsari I', 'Batsari II', 'Batsari III', 'Batsari IV', 'Batsari V']],
    ['Baure', ['Baure I', 'Baure II', 'Baure III', 'Baure IV']],
    ['Bindawa', ['Bindawa I', 'Bindawa II', 'Bindawa III', 'Bindawa IV']],
    ['Charanchi', ['Charanchi I', 'Charanchi II', 'Charanchi III', 'Charanchi IV']],
    ['Dan Musa', ['Dan Musa I', 'Dan Musa II', 'Dan Musa III', 'Dan Musa IV']],
    ['Dandume', ['Dandume I', 'Dandume II', 'Dandume III', 'Dandume IV']],
    ['Danja', ['Danja I', 'Danja II', 'Danja III', 'Danja IV']],
    ['Daura', ['Daura I', 'Daura II', 'Daura III', 'Daura IV', 'Daura V']],
    ['Dutsi', ['Dutsi I', 'Dutsi II', 'Dutsi III', 'Dutsi IV']],
    ['Dutsin-Ma', ['Dutsin-Ma I', 'Dutsin-Ma II', 'Dutsin-Ma III', 'Dutsin-Ma IV', 'Dutsin-Ma V']],
    ['Faskari', ['Faskari I', 'Faskari II', 'Faskari III', 'Faskari IV', 'Faskari V']],
    ['Funtua', ['Funtua I', 'Funtua II', 'Funtua III', 'Funtua IV', 'Funtua V']],
    ['Ingawa', ['Ingawa I', 'Ingawa II', 'Ingawa III', 'Ingawa IV']],
    ['Jibia', ['Jibia I', 'Jibia II', 'Jibia III', 'Jibia IV', 'Jibia V']],
    ['Kafur', ['Kafur I', 'Kafur II', 'Kafur III', 'Kafur IV']],
    ['Kaita', ['Kaita I', 'Kaita II', 'Kaita III', 'Kaita IV']],
    ['Kankara', ['Kankara I', 'Kankara II', 'Kankara III', 'Kankara IV', 'Kankara V']],
    ['Kankia', ['Kankia I', 'Kankia II', 'Kankia III', 'Kankia IV']],
    ['Katsina', ['Katsina I', 'Katsina II', 'Katsina III', 'Katsina IV', 'Katsina V', 'Katsina VI']],
    ['Kurfi', ['Kurfi I', 'Kurfi II', 'Kurfi III', 'Kurfi IV']],
    ['Kusada', ['Kusada I', 'Kusada II', 'Kusada III', 'Kusada IV']],
    ["Mai'Adua", ["Mai'Adua I", "Mai'Adua II", "Mai'Adua III", "Mai'Adua IV"]],
    ['Malumfashi', ['Malumfashi I', 'Malumfashi II', 'Malumfashi III', 'Malumfashi IV', 'Malumfashi V']],
    ['Mani', ['Mani I', 'Mani II', 'Mani III', 'Mani IV']],
    ['Mashi', ['Mashi I', 'Mashi II', 'Mashi III', 'Mashi IV']],
    ['Matazu', ['Matazu I', 'Matazu II', 'Matazu III', 'Matazu IV']],
    ['Musawa', ['Musawa I', 'Musawa II', 'Musawa III', 'Musawa IV', 'Musawa V']],
    ['Rimi', ['Rimi I', 'Rimi II', 'Rimi III', 'Rimi IV']],
    ['Sabuwa', ['Sabuwa I', 'Sabuwa II', 'Sabuwa III', 'Sabuwa IV']],
    ['Safana', ['Safana I', 'Safana II', 'Safana III', 'Safana IV']],
    ['Sandamu', ['Sandamu I', 'Sandamu II', 'Sandamu III', 'Sandamu IV']],
    ['Zango', ['Zango I', 'Zango II', 'Zango III', 'Zango IV', 'Zango V']],
  ]),
  makeState('kebbi', 'Kebbi', [
    ['Aleiro', ['Aleiro I', 'Aleiro II', 'Aleiro III', 'Aleiro IV']],
    ['Arewa Dandi', ['Arewa Dandi I', 'Arewa Dandi II', 'Arewa Dandi III', 'Arewa Dandi IV']],
    ['Argungu', ['Argungu I', 'Argungu II', 'Argungu III', 'Argungu IV', 'Argungu V']],
    ['Augie', ['Augie I', 'Augie II', 'Augie III', 'Augie IV']],
    ['Bagudo', ['Bagudo I', 'Bagudo II', 'Bagudo III', 'Bagudo IV', 'Bagudo V']],
    ['Birnin Kebbi', ['Birnin Kebbi I', 'Birnin Kebbi II', 'Birnin Kebbi III', 'Birnin Kebbi IV', 'Birnin Kebbi V']],
    ['Bunza', ['Bunza I', 'Bunza II', 'Bunza III', 'Bunza IV']],
    ['Dandi', ['Dandi I', 'Dandi II', 'Dandi III', 'Dandi IV']],
    ['Fakai', ['Fakai I', 'Fakai II', 'Fakai III', 'Fakai IV']],
    ['Gwandu', ['Gwandu I', 'Gwandu II', 'Gwandu III', 'Gwandu IV', 'Gwandu V']],
    ['Jega', ['Jega I', 'Jega II', 'Jega III', 'Jega IV', 'Jega V']],
    ['Kalgo', ['Kalgo I', 'Kalgo II', 'Kalgo III', 'Kalgo IV']],
    ['Koko/Besse', ['Koko I', 'Koko II', 'Koko III', 'Besse I', 'Besse II']],
    ['Maiyama', ['Maiyama I', 'Maiyama II', 'Maiyama III', 'Maiyama IV', 'Maiyama V']],
    ['Ngaski', ['Ngaski I', 'Ngaski II', 'Ngaski III', 'Ngaski IV']],
    ['Sakaba', ['Sakaba I', 'Sakaba II', 'Sakaba III', 'Sakaba IV']],
    ['Shanga', ['Shanga I', 'Shanga II', 'Shanga III', 'Shanga IV']],
    ['Suru', ['Suru I', 'Suru II', 'Suru III', 'Suru IV']],
    ['Wasagu/Danko', ['Wasagu I', 'Wasagu II', 'Wasagu III', 'Danko I', 'Danko II']],
    ['Yauri', ['Yauri I', 'Yauri II', 'Yauri III', 'Yauri IV', 'Yauri V']],
    ['Zuru', ['Zuru I', 'Zuru II', 'Zuru III', 'Zuru IV', 'Zuru V']],
  ]),
  makeState('kogi', 'Kogi', [
    ['Adavi', ['Adavi I', 'Adavi II', 'Adavi III', 'Adavi IV', 'Adavi V']],
    ['Ajaokuta', ['Ajaokuta I', 'Ajaokuta II', 'Ajaokuta III', 'Ajaokuta IV']],
    ['Ankpa', ['Ankpa I', 'Ankpa II', 'Ankpa III', 'Ankpa IV', 'Ankpa V']],
    ['Bassa', ['Bassa I', 'Bassa II', 'Bassa III', 'Bassa IV', 'Bassa V']],
    ['Dekina', ['Dekina I', 'Dekina II', 'Dekina III', 'Dekina IV', 'Dekina V']],
    ['Ibaji', ['Ibaji I', 'Ibaji II', 'Ibaji III', 'Ibaji IV']],
    ['Idah', ['Idah I', 'Idah II', 'Idah III', 'Idah IV', 'Idah V']],
    ['Igalamela Odolu', ['Igalamela I', 'Igalamela II', 'Igalamela III', 'Odolu I', 'Odolu II']],
    ['Ijumu', ['Ijumu I', 'Ijumu II', 'Ijumu III', 'Ijumu IV']],
    ['Kabba/Bunu', ['Kabba I', 'Kabba II', 'Kabba III', 'Bunu I', 'Bunu II']],
    ['Kogi', ['Kogi I', 'Kogi II', 'Kogi III', 'Kogi IV', 'Kogi V']],
    ['Lokoja', ['Lokoja I', 'Lokoja II', 'Lokoja III', 'Lokoja IV', 'Lokoja V', 'Lokoja VI']],
    ['Mopa Muro', ['Mopa I', 'Mopa II', 'Mopa III', 'Muro I', 'Muro II']],
    ['Ofu', ['Ofu I', 'Ofu II', 'Ofu III', 'Ofu IV', 'Ofu V']],
    ['Ogori/Magongo', ['Ogori I', 'Ogori II', 'Ogori III', 'Magongo I', 'Magongo II']],
    ['Okehi', ['Okehi I', 'Okehi II', 'Okehi III', 'Okehi IV', 'Okehi V']],
    ['Okene', ['Okene I', 'Okene II', 'Okene III', 'Okene IV', 'Okene V', 'Okene VI']],
    ['Olamaboro', ['Olamaboro I', 'Olamaboro II', 'Olamaboro III', 'Olamaboro IV']],
    ['Omala', ['Omala I', 'Omala II', 'Omala III', 'Omala IV']],
    ['Yagba East', ['Yagba East I', 'Yagba East II', 'Yagba East III', 'Yagba East IV', 'Yagba East V']],
    ['Yagba West', ['Yagba West I', 'Yagba West II', 'Yagba West III', 'Yagba West IV']],
  ]),
  makeState('kwara', 'Kwara', [
    ['Asa', ['Asa I', 'Asa II', 'Asa III', 'Asa IV', 'Asa V']],
    ['Baruten', ['Baruten I', 'Baruten II', 'Baruten III', 'Baruten IV', 'Baruten V']],
    ['Edu', ['Edu I', 'Edu II', 'Edu III', 'Edu IV', 'Edu V']],
    ['Ekiti', ['Ekiti I', 'Ekiti II', 'Ekiti III', 'Ekiti IV']],
    ['Ifelodun', ['Ifelodun I', 'Ifelodun II', 'Ifelodun III', 'Ifelodun IV', 'Ifelodun V']],
    ['Ilorin East', ['Ilorin East I', 'Ilorin East II', 'Ilorin East III', 'Ilorin East IV', 'Ilorin East V']],
    ['Ilorin South', ['Ilorin South I', 'Ilorin South II', 'Ilorin South III', 'Ilorin South IV', 'Ilorin South V']],
    ['Ilorin West', ['Ilorin West I', 'Ilorin West II', 'Ilorin West III', 'Ilorin West IV', 'Ilorin West V', 'Ilorin West VI']],
    ['Irepodun', ['Irepodun I', 'Irepodun II', 'Irepodun III', 'Irepodun IV', 'Irepodun V']],
    ['Isin', ['Isin I', 'Isin II', 'Isin III', 'Isin IV']],
    ['Kaiama', ['Kaiama I', 'Kaiama II', 'Kaiama III', 'Kaiama IV', 'Kaiama V']],
    ['Moro', ['Moro I', 'Moro II', 'Moro III', 'Moro IV', 'Moro V']],
    ['Offa', ['Offa I', 'Offa II', 'Offa III', 'Offa IV', 'Offa V']],
    ['Oke Ero', ['Oke Ero I', 'Oke Ero II', 'Oke Ero III', 'Oke Ero IV']],
    ['Oyun', ['Oyun I', 'Oyun II', 'Oyun III', 'Oyun IV', 'Oyun V']],
    ['Pategi', ['Pategi I', 'Pategi II', 'Pategi III', 'Pategi IV']],
  ]),
  makeState('lagos', 'Lagos', [
    ['Agege', ['Agege I', 'Agege II', 'Agege III', 'Agege IV', 'Agege V']],
    ['Ajeromi-Ifelodun', ['Ajeromi I', 'Ajeromi II', 'Ajeromi III', 'Ajeromi IV', 'Ajeromi V']],
    ['Alimosho', ['Alimosho I', 'Alimosho II', 'Alimosho III', 'Alimosho IV', 'Alimosho V', 'Alimosho VI']],
    ['Amuwo-Odofin', ['Amuwo-Odofin I', 'Amuwo-Odofin II', 'Amuwo-Odofin III', 'Amuwo-Odofin IV', 'Amuwo-Odofin V']],
    ['Apapa', ['Apapa I', 'Apapa II', 'Apapa III', 'Apapa IV', 'Apapa V']],
    ['Badagry', ['Badagry I', 'Badagry II', 'Badagry III', 'Badagry IV', 'Badagry V']],
    ['Epe', ['Epe I', 'Epe II', 'Epe III', 'Epe IV', 'Epe V']],
    ['Eti-Osa', ['Lekki Phase 1', 'Victoria Island', 'Ikoyi', 'Ajah', 'Sangotedo', 'Ikate']],
    ['Ibeju-Lekki', ['Ibeju-Lekki I', 'Ibeju-Lekki II', 'Ibeju-Lekki III', 'Ibeju-Lekki IV']],
    ['Ifako-Ijaiye', ['Ifako-Ijaiye I', 'Ifako-Ijaiye II', 'Ifako-Ijaiye III', 'Ifako-Ijaiye IV', 'Ifako-Ijaiye V']],
    ['Ikeja', ['Alausa', 'Agidingbi', 'Oregun', 'Ojodu', 'Onigbongbo', 'Maryland']],
    ['Ikorodu', ['Ikorodu I', 'Ikorodu II', 'Ikorodu III', 'Ikorodu IV', 'Ikorodu V', 'Ikorodu VI']],
    ['Kosofe', ['Kosofe I', 'Kosofe II', 'Kosofe III', 'Kosofe IV', 'Kosofe V']],
    ['Lagos Island', ['Lagos Island I', 'Lagos Island II', 'Lagos Island III', 'Lagos Island IV', 'Lagos Island V']],
    ['Lagos Mainland', ['Lagos Mainland I', 'Lagos Mainland II', 'Lagos Mainland III', 'Lagos Mainland IV', 'Lagos Mainland V']],
    ['Mushin', ['Mushin I', 'Mushin II', 'Mushin III', 'Mushin IV', 'Mushin V']],
    ['Ojo', ['Ojo I', 'Ojo II', 'Ojo III', 'Ojo IV', 'Ojo V']],
    ['Oshodi-Isolo', ['Oshodi-Isolo I', 'Oshodi-Isolo II', 'Oshodi-Isolo III', 'Oshodi-Isolo IV', 'Oshodi-Isolo V']],
    ['Shomolu', ['Shomolu I', 'Shomolu II', 'Shomolu III', 'Shomolu IV', 'Shomolu V']],
    ['Surulere', ['Aguda', 'Itire', 'Bode Thomas', 'Ijeshatedo', 'Shitta', 'Randle']],
  ]),
  makeState('nasarawa', 'Nasarawa', [
    ['Akwanga', ['Akwanga I', 'Akwanga II', 'Akwanga III', 'Akwanga IV', 'Akwanga V']],
    ['Awe', ['Awe I', 'Awe II', 'Awe III', 'Awe IV', 'Awe V']],
    ['Doma', ['Doma I', 'Doma II', 'Doma III', 'Doma IV', 'Doma V']],
    ['Karu', ['Karu I', 'Karu II', 'Karu III', 'Karu IV', 'Karu V']],
    ['Keana', ['Keana I', 'Keana II', 'Keana III', 'Keana IV']],
    ['Keffi', ['Keffi I', 'Keffi II', 'Keffi III', 'Keffi IV', 'Keffi V']],
    ['Kokona', ['Kokona I', 'Kokona II', 'Kokona III', 'Kokona IV', 'Kokona V']],
    ['Lafia', ['Lafia I', 'Lafia II', 'Lafia III', 'Lafia IV', 'Lafia V', 'Lafia VI']],
    ['Nasarawa', ['Nasarawa I', 'Nasarawa II', 'Nasarawa III', 'Nasarawa IV', 'Nasarawa V']],
    ['Nasarawa Egon', ['Nasarawa Egon I', 'Nasarawa Egon II', 'Nasarawa Egon III', 'Nasarawa Egon IV']],
    ['Obi', ['Obi I', 'Obi II', 'Obi III', 'Obi IV']],
    ['Toto', ['Toto I', 'Toto II', 'Toto III', 'Toto IV', 'Toto V']],
    ['Wamba', ['Wamba I', 'Wamba II', 'Wamba III', 'Wamba IV', 'Wamba V']],
  ]),
  makeState('niger', 'Niger', [
    ['Agaie', ['Agaie I', 'Agaie II', 'Agaie III', 'Agaie IV', 'Agaie V']],
    ['Agwara', ['Agwara I', 'Agwara II', 'Agwara III', 'Agwara IV']],
    ['Bida', ['Bida I', 'Bida II', 'Bida III', 'Bida IV', 'Bida V']],
    ['Borgu', ['Borgu I', 'Borgu II', 'Borgu III', 'Borgu IV', 'Borgu V']],
    ['Bosso', ['Bosso I', 'Bosso II', 'Bosso III', 'Bosso IV', 'Bosso V']],
    ['Chanchaga', ['Chanchaga I', 'Chanchaga II', 'Chanchaga III', 'Chanchaga IV', 'Chanchaga V']],
    ['Edati', ['Edati I', 'Edati II', 'Edati III', 'Edati IV']],
    ['Gbako', ['Gbako I', 'Gbako II', 'Gbako III', 'Gbako IV']],
    ['Gurara', ['Gurara I', 'Gurara II', 'Gurara III', 'Gurara IV']],
    ['Katcha', ['Katcha I', 'Katcha II', 'Katcha III', 'Katcha IV', 'Katcha V']],
    ['Kontagora', ['Kontagora I', 'Kontagora II', 'Kontagora III', 'Kontagora IV', 'Kontagora V']],
    ['Lapai', ['Lapai I', 'Lapai II', 'Lapai III', 'Lapai IV', 'Lapai V']],
    ['Lavun', ['Lavun I', 'Lavun II', 'Lavun III', 'Lavun IV', 'Lavun V']],
    ['Magama', ['Magama I', 'Magama II', 'Magama III', 'Magama IV']],
    ['Mariga', ['Mariga I', 'Mariga II', 'Mariga III', 'Mariga IV']],
    ['Mashegu', ['Mashegu I', 'Mashegu II', 'Mashegu III', 'Mashegu IV']],
    ['Mokwa', ['Mokwa I', 'Mokwa II', 'Mokwa III', 'Mokwa IV', 'Mokwa V']],
    ['Munya', ['Munya I', 'Munya II', 'Munya III', 'Munya IV']],
    ['Paikoro', ['Paikoro I', 'Paikoro II', 'Paikoro III', 'Paikoro IV']],
    ['Rafi', ['Rafi I', 'Rafi II', 'Rafi III', 'Rafi IV', 'Rafi V']],
    ['Rijau', ['Rijau I', 'Rijau II', 'Rijau III', 'Rijau IV', 'Rijau V']],
    ['Shiroro', ['Shiroro I', 'Shiroro II', 'Shiroro III', 'Shiroro IV', 'Shiroro V']],
    ['Suleja', ['Suleja I', 'Suleja II', 'Suleja III', 'Suleja IV', 'Suleja V']],
    ['Tafa', ['Tafa I', 'Tafa II', 'Tafa III', 'Tafa IV']],
    ['Wushishi', ['Wushishi I', 'Wushishi II', 'Wushishi III', 'Wushishi IV']],
  ]),
  makeState('ogun', 'Ogun', [
    ['Abeokuta North', ['Abeokuta North I', 'Abeokuta North II', 'Abeokuta North III', 'Abeokuta North IV', 'Abeokuta North V']],
    ['Abeokuta South', ['Abeokuta South I', 'Abeokuta South II', 'Abeokuta South III', 'Abeokuta South IV', 'Abeokuta South V']],
    ['Ado-Odo/Ota', ['Ado-Odo I', 'Ado-Odo II', 'Ado-Odo III', 'Ota I', 'Ota II', 'Ota III']],
    ['Egbado North', ['Egbado North I', 'Egbado North II', 'Egbado North III', 'Egbado North IV']],
    ['Egbado South', ['Egbado South I', 'Egbado South II', 'Egbado South III', 'Egbado South IV']],
    ['Ewekoro', ['Ewekoro I', 'Ewekoro II', 'Ewekoro III', 'Ewekoro IV']],
    ['Ifo', ['Ifo I', 'Ifo II', 'Ifo III', 'Ifo IV', 'Ifo V']],
    ['Ijebu East', ['Ijebu East I', 'Ijebu East II', 'Ijebu East III', 'Ijebu East IV']],
    ['Ijebu North', ['Ijebu North I', 'Ijebu North II', 'Ijebu North III', 'Ijebu North IV', 'Ijebu North V']],
    ['Ijebu North East', ['Ijebu North East I', 'Ijebu North East II', 'Ijebu North East III', 'Ijebu North East IV']],
    ['Ijebu Ode', ['Ijebu Ode I', 'Ijebu Ode II', 'Ijebu Ode III', 'Ijebu Ode IV', 'Ijebu Ode V']],
    ['Ikenne', ['Ikenne I', 'Ikenne II', 'Ikenne III', 'Ikenne IV']],
    ['Imeko Afon', ['Imeko Afon I', 'Imeko Afon II', 'Imeko Afon III', 'Imeko Afon IV']],
    ['Ipokia', ['Ipokia I', 'Ipokia II', 'Ipokia III', 'Ipokia IV']],
    ['Obafemi Owode', ['Obafemi Owode I', 'Obafemi Owode II', 'Obafemi Owode III', 'Obafemi Owode IV', 'Obafemi Owode V']],
    ['Odeda', ['Odeda I', 'Odeda II', 'Odeda III', 'Odeda IV']],
    ['Odogbolu', ['Odogbolu I', 'Odogbolu II', 'Odogbolu III', 'Odogbolu IV']],
    ['Ogun Waterside', ['Ogun Waterside I', 'Ogun Waterside II', 'Ogun Waterside III', 'Ogun Waterside IV']],
    ['Remo North', ['Remo North I', 'Remo North II', 'Remo North III', 'Remo North IV']],
    ['Sagamu', ['Sagamu I', 'Sagamu II', 'Sagamu III', 'Sagamu IV', 'Sagamu V']],
  ]),
  makeState('ondo', 'Ondo', [
    ['Akoko North East', ['Akoko North East I', 'Akoko North East II', 'Akoko North East III', 'Akoko North East IV']],
    ['Akoko North West', ['Akoko North West I', 'Akoko North West II', 'Akoko North West III', 'Akoko North West IV']],
    ['Akoko South East', ['Akoko South East I', 'Akoko South East II', 'Akoko South East III', 'Akoko South East IV']],
    ['Akoko South West', ['Akoko South West I', 'Akoko South West II', 'Akoko South West III', 'Akoko South West IV', 'Akoko South West V']],
    ['Akure North', ['Akure North I', 'Akure North II', 'Akure North III', 'Akure North IV']],
    ['Akure South', ['Akure South I', 'Akure South II', 'Akure South III', 'Akure South IV', 'Akure South V', 'Akure South VI']],
    ['Ese Odo', ['Ese Odo I', 'Ese Odo II', 'Ese Odo III', 'Ese Odo IV']],
    ['Idanre', ['Idanre I', 'Idanre II', 'Idanre III', 'Idanre IV', 'Idanre V']],
    ['Ifedore', ['Ifedore I', 'Ifedore II', 'Ifedore III', 'Ifedore IV']],
    ['Ilaje', ['Ilaje I', 'Ilaje II', 'Ilaje III', 'Ilaje IV', 'Ilaje V']],
    ['Ile Oluji/Okeigbo', ['Ile Oluji I', 'Ile Oluji II', 'Ile Oluji III', 'Okeigbo I', 'Okeigbo II']],
    ['Irele', ['Irele I', 'Irele II', 'Irele III', 'Irele IV']],
    ['Odigbo', ['Odigbo I', 'Odigbo II', 'Odigbo III', 'Odigbo IV', 'Odigbo V']],
    ['Okitipupa', ['Okitipupa I', 'Okitipupa II', 'Okitipupa III', 'Okitipupa IV', 'Okitipupa V']],
    ['Ondo East', ['Ondo East I', 'Ondo East II', 'Ondo East III', 'Ondo East IV']],
    ['Ondo West', ['Ondo West I', 'Ondo West II', 'Ondo West III', 'Ondo West IV', 'Ondo West V']],
    ['Ose', ['Ose I', 'Ose II', 'Ose III', 'Ose IV', 'Ose V']],
    ['Owo', ['Owo I', 'Owo II', 'Owo III', 'Owo IV', 'Owo V']],
  ]),
  makeState('osun', 'Osun', [
    ['Aiyedaade', ['Aiyedaade I', 'Aiyedaade II', 'Aiyedaade III', 'Aiyedaade IV']],
    ['Aiyedire', ['Aiyedire I', 'Aiyedire II', 'Aiyedire III', 'Aiyedire IV']],
    ['Atakumosa East', ['Atakumosa East I', 'Atakumosa East II', 'Atakumosa East III', 'Atakumosa East IV']],
    ['Atakumosa West', ['Atakumosa West I', 'Atakumosa West II', 'Atakumosa West III', 'Atakumosa West IV']],
    ['Boluwaduro', ['Boluwaduro I', 'Boluwaduro II', 'Boluwaduro III', 'Boluwaduro IV']],
    ['Boripe', ['Boripe I', 'Boripe II', 'Boripe III', 'Boripe IV', 'Boripe V']],
    ['Ede North', ['Ede North I', 'Ede North II', 'Ede North III', 'Ede North IV']],
    ['Ede South', ['Ede South I', 'Ede South II', 'Ede South III', 'Ede South IV']],
    ['Egbedore', ['Egbedore I', 'Egbedore II', 'Egbedore III', 'Egbedore IV']],
    ['Ejigbo', ['Ejigbo I', 'Ejigbo II', 'Ejigbo III', 'Ejigbo IV', 'Ejigbo V']],
    ['Ife Central', ['Ife Central I', 'Ife Central II', 'Ife Central III', 'Ife Central IV', 'Ife Central V']],
    ['Ife East', ['Ife East I', 'Ife East II', 'Ife East III', 'Ife East IV']],
    ['Ife North', ['Ife North I', 'Ife North II', 'Ife North III', 'Ife North IV']],
    ['Ife South', ['Ife South I', 'Ife South II', 'Ife South III', 'Ife South IV']],
    ['Ifedayo', ['Ifedayo I', 'Ifedayo II', 'Ifedayo III', 'Ifedayo IV']],
    ['Ifelodun', ['Ifelodun I', 'Ifelodun II', 'Ifelodun III', 'Ifelodun IV', 'Ifelodun V']],
    ['Ila', ['Ila I', 'Ila II', 'Ila III', 'Ila IV', 'Ila V']],
    ['Ilesa East', ['Ilesa East I', 'Ilesa East II', 'Ilesa East III', 'Ilesa East IV']],
    ['Ilesa West', ['Ilesa West I', 'Ilesa West II', 'Ilesa West III', 'Ilesa West IV', 'Ilesa West V']],
    ['Irepodun', ['Irepodun I', 'Irepodun II', 'Irepodun III', 'Irepodun IV', 'Irepodun V']],
    ['Irewole', ['Irewole I', 'Irewole II', 'Irewole III', 'Irewole IV']],
    ['Isokan', ['Isokan I', 'Isokan II', 'Isokan III', 'Isokan IV']],
    ['Iwo', ['Iwo I', 'Iwo II', 'Iwo III', 'Iwo IV', 'Iwo V']],
    ['Obokun', ['Obokun I', 'Obokun II', 'Obokun III', 'Obokun IV']],
    ['Odo Otin', ['Odo Otin I', 'Odo Otin II', 'Odo Otin III', 'Odo Otin IV']],
    ['Ola Oluwa', ['Ola Oluwa I', 'Ola Oluwa II', 'Ola Oluwa III', 'Ola Oluwa IV']],
    ['Olorunda', ['Olorunda I', 'Olorunda II', 'Olorunda III', 'Olorunda IV', 'Olorunda V']],
    ['Oriade', ['Oriade I', 'Oriade II', 'Oriade III', 'Oriade IV', 'Oriade V']],
    ['Orolu', ['Orolu I', 'Orolu II', 'Orolu III', 'Orolu IV']],
    ['Osogbo', ['Osogbo I', 'Osogbo II', 'Osogbo III', 'Osogbo IV', 'Osogbo V', 'Osogbo VI']],
  ]),
  makeState('oyo', 'Oyo', [
    ['Afijio', ['Afijio I', 'Afijio II', 'Afijio III', 'Afijio IV']],
    ['Akinyele', ['Akinyele I', 'Akinyele II', 'Akinyele III', 'Akinyele IV', 'Akinyele V']],
    ['Atiba', ['Atiba I', 'Atiba II', 'Atiba III', 'Atiba IV', 'Atiba V']],
    ['Atisbo', ['Atisbo I', 'Atisbo II', 'Atisbo III', 'Atisbo IV']],
    ['Egbeda', ['Egbeda I', 'Egbeda II', 'Egbeda III', 'Egbeda IV', 'Egbeda V']],
    ['Ibadan North', ['Agodi', 'Bodija', 'Sango', 'Yemetu', 'Agodi GRA', 'Oke-Ado']],
    ['Ibadan North East', ['Ibadan North East I', 'Ibadan North East II', 'Ibadan North East III', 'Ibadan North East IV', 'Ibadan North East V']],
    ['Ibadan North West', ['Ibadan North West I', 'Ibadan North West II', 'Ibadan North West III', 'Ibadan North West IV']],
    ['Ibadan South East', ['Ibadan South East I', 'Ibadan South East II', 'Ibadan South East III', 'Ibadan South East IV', 'Ibadan South East V']],
    ['Ibadan South West', ['Oke-Ado', 'Iyaganku', 'Oluyole', 'Oke-Bola', 'Oke-Foko', 'Oke-Itunu']],
    ['Ibarapa Central', ['Ibarapa Central I', 'Ibarapa Central II', 'Ibarapa Central III', 'Ibarapa Central IV']],
    ['Ibarapa East', ['Ibarapa East I', 'Ibarapa East II', 'Ibarapa East III', 'Ibarapa East IV']],
    ['Ibarapa North', ['Ibarapa North I', 'Ibarapa North II', 'Ibarapa North III', 'Ibarapa North IV']],
    ['Ido', ['Ido I', 'Ido II', 'Ido III', 'Ido IV', 'Ido V']],
    ['Irepo', ['Irepo I', 'Irepo II', 'Irepo III', 'Irepo IV']],
    ['Iseyin', ['Iseyin I', 'Iseyin II', 'Iseyin III', 'Iseyin IV', 'Iseyin V']],
    ['Itesiwaju', ['Itesiwaju I', 'Itesiwaju II', 'Itesiwaju III', 'Itesiwaju IV']],
    ['Iwajowa', ['Iwajowa I', 'Iwajowa II', 'Iwajowa III', 'Iwajowa IV']],
    ['Kajola', ['Kajola I', 'Kajola II', 'Kajola III', 'Kajola IV', 'Kajola V']],
    ['Lagelu', ['Lagelu I', 'Lagelu II', 'Lagelu III', 'Lagelu IV', 'Lagelu V']],
    ['Ogbomosho North', ['Ogbomosho North I', 'Ogbomosho North II', 'Ogbomosho North III', 'Ogbomosho North IV', 'Ogbomosho North V']],
    ['Ogbomosho South', ['Ogbomosho South I', 'Ogbomosho South II', 'Ogbomosho South III', 'Ogbomosho South IV']],
    ['Ogo Oluwa', ['Ogo Oluwa I', 'Ogo Oluwa II', 'Ogo Oluwa III', 'Ogo Oluwa IV']],
    ['Olorunsogo', ['Olorunsogo I', 'Olorunsogo II', 'Olorunsogo III', 'Olorunsogo IV']],
    ['Oluyole', ['Oluyole I', 'Oluyole II', 'Oluyole III', 'Oluyole IV', 'Oluyole V']],
    ['Ona Ara', ['Ona Ara I', 'Ona Ara II', 'Ona Ara III', 'Ona Ara IV', 'Ona Ara V']],
    ['Orelope', ['Orelope I', 'Orelope II', 'Orelope III', 'Orelope IV']],
    ['Ori Ire', ['Ori Ire I', 'Ori Ire II', 'Ori Ire III', 'Ori Ire IV']],
    ['Oyo East', ['Oyo East I', 'Oyo East II', 'Oyo East III', 'Oyo East IV', 'Oyo East V']],
    ['Oyo West', ['Oyo West I', 'Oyo West II', 'Oyo West III', 'Oyo West IV', 'Oyo West V']],
    ['Saki East', ['Saki East I', 'Saki East II', 'Saki East III', 'Saki East IV']],
    ['Saki West', ['Saki West I', 'Saki West II', 'Saki West III', 'Saki West IV', 'Saki West V']],
    ['Surulere', ['Surulere I', 'Surulere II', 'Surulere III', 'Surulere IV']],
  ]),
  makeState('plateau', 'Plateau', [
    ['Barkin Ladi', ['Barkin Ladi I', 'Barkin Ladi II', 'Barkin Ladi III', 'Barkin Ladi IV', 'Barkin Ladi V']],
    ['Bassa', ['Bassa I', 'Bassa II', 'Bassa III', 'Bassa IV', 'Bassa V']],
    ['Bokkos', ['Bokkos I', 'Bokkos II', 'Bokkos III', 'Bokkos IV', 'Bokkos V']],
    ['Jos East', ['Jos East I', 'Jos East II', 'Jos East III', 'Jos East IV']],
    ['Jos North', ['Jos North I', 'Jos North II', 'Jos North III', 'Jos North IV', 'Jos North V', 'Jos North VI']],
    ['Jos South', ['Jos South I', 'Jos South II', 'Jos South III', 'Jos South IV', 'Jos South V']],
    ['Kanam', ['Kanam I', 'Kanam II', 'Kanam III', 'Kanam IV', 'Kanam V']],
    ['Kanke', ['Kanke I', 'Kanke II', 'Kanke III', 'Kanke IV']],
    ['Langtang North', ['Langtang North I', 'Langtang North II', 'Langtang North III', 'Langtang North IV']],
    ['Langtang South', ['Langtang South I', 'Langtang South II', 'Langtang South III', 'Langtang South IV']],
    ['Mangu', ['Mangu I', 'Mangu II', 'Mangu III', 'Mangu IV', 'Mangu V']],
    ['Mikang', ['Mikang I', 'Mikang II', 'Mikang III', 'Mikang IV']],
    ['Pankshin', ['Pankshin I', 'Pankshin II', 'Pankshin III', 'Pankshin IV', 'Pankshin V']],
    ["Qua'an Pan", ["Qua'an Pan I", "Qua'an Pan II", "Qua'an Pan III", "Qua'an Pan IV"]],
    ['Riyom', ['Riyom I', 'Riyom II', 'Riyom III', 'Riyom IV']],
    ['Shendam', ['Shendam I', 'Shendam II', 'Shendam III', 'Shendam IV', 'Shendam V']],
    ['Wase', ['Wase I', 'Wase II', 'Wase III', 'Wase IV', 'Wase V']],
  ]),
  makeState('rivers', 'Rivers', [
    ['Abua/Odual', ['Abua I', 'Abua II', 'Abua III', 'Odual I', 'Odual II']],
    ['Ahoada East', ['Ahoada East I', 'Ahoada East II', 'Ahoada East III', 'Ahoada East IV', 'Ahoada East V']],
    ['Ahoada West', ['Ahoada West I', 'Ahoada West II', 'Ahoada West III', 'Ahoada West IV']],
    ['Akuku-Toru', ['Akuku-Toru I', 'Akuku-Toru II', 'Akuku-Toru III', 'Akuku-Toru IV']],
    ['Andoni', ['Andoni I', 'Andoni II', 'Andoni III', 'Andoni IV', 'Andoni V']],
    ['Asari-Toru', ['Asari-Toru I', 'Asari-Toru II', 'Asari-Toru III', 'Asari-Toru IV']],
    ['Bonny', ['Bonny I', 'Bonny II', 'Bonny III', 'Bonny IV', 'Bonny V']],
    ['Degema', ['Degema I', 'Degema II', 'Degema III', 'Degema IV', 'Degema V']],
    ['Eleme', ['Eleme I', 'Eleme II', 'Eleme III', 'Eleme IV']],
    ['Emohua', ['Emohua I', 'Emohua II', 'Emohua III', 'Emohua IV', 'Emohua V']],
    ['Etche', ['Etche I', 'Etche II', 'Etche III', 'Etche IV', 'Etche V']],
    ['Gokana', ['Gokana I', 'Gokana II', 'Gokana III', 'Gokana IV']],
    ['Ikwerre', ['Ikwerre I', 'Ikwerre II', 'Ikwerre III', 'Ikwerre IV', 'Ikwerre V']],
    ['Khana', ['Khana I', 'Khana II', 'Khana III', 'Khana IV', 'Khana V']],
    ['Obio-Akpor', ['Rumuigbo', 'Ozuoba', 'Rumuola', 'Rumuodara', 'Rumuepirikom', 'Rumuokwuta']],
    ['Ogba/Egbema/Ndoni', ['Ogba I', 'Ogba II', 'Ogba III', 'Egbema I', 'Egbema II', 'Ndoni I']],
    ['Ogu/Bolo', ['Ogu I', 'Ogu II', 'Bolo I', 'Bolo II']],
    ['Okrika', ['Okrika I', 'Okrika II', 'Okrika III', 'Okrika IV']],
    ['Omuma', ['Omuma I', 'Omuma II', 'Omuma III', 'Omuma IV']],
    ['Opobo/Nkoro', ['Opobo I', 'Opobo II', 'Opobo III', 'Nkoro I', 'Nkoro II']],
    ['Oyigbo', ['Oyigbo I', 'Oyigbo II', 'Oyigbo III', 'Oyigbo IV']],
    ['Port Harcourt', ['D-Line', 'GRA Phase 1', 'GRA Phase 2', 'Rumuola', 'Diobu', 'Borokiri', 'Rumuobiakani']],
    ['Tai', ['Tai I', 'Tai II', 'Tai III', 'Tai IV']],
  ]),
  makeState('sokoto', 'Sokoto', [
    ['Binji', ['Binji I', 'Binji II', 'Binji III', 'Binji IV']],
    ['Bodinga', ['Bodinga I', 'Bodinga II', 'Bodinga III', 'Bodinga IV']],
    ['Dange Shuni', ['Dange Shuni I', 'Dange Shuni II', 'Dange Shuni III', 'Dange Shuni IV', 'Dange Shuni V']],
    ['Gada', ['Gada I', 'Gada II', 'Gada III', 'Gada IV']],
    ['Goronyo', ['Goronyo I', 'Goronyo II', 'Goronyo III', 'Goronyo IV']],
    ['Gudu', ['Gudu I', 'Gudu II', 'Gudu III', 'Gudu IV']],
    ['Gwadabawa', ['Gwadabawa I', 'Gwadabawa II', 'Gwadabawa III', 'Gwadabawa IV', 'Gwadabawa V']],
    ['Illela', ['Illela I', 'Illela II', 'Illela III', 'Illela IV', 'Illela V']],
    ['Isa', ['Isa I', 'Isa II', 'Isa III', 'Isa IV']],
    ['Kebbe', ['Kebbe I', 'Kebbe II', 'Kebbe III', 'Kebbe IV']],
    ['Kware', ['Kware I', 'Kware II', 'Kware III', 'Kware IV']],
    ['Rabah', ['Rabah I', 'Rabah II', 'Rabah III', 'Rabah IV', 'Rabah V']],
    ['Sabon Birni', ['Sabon Birni I', 'Sabon Birni II', 'Sabon Birni III', 'Sabon Birni IV', 'Sabon Birni V']],
    ['Shagari', ['Shagari I', 'Shagari II', 'Shagari III', 'Shagari IV']],
    ['Silame', ['Silame I', 'Silame II', 'Silame III', 'Silame IV']],
    ['Sokoto North', ['Sokoto North I', 'Sokoto North II', 'Sokoto North III', 'Sokoto North IV', 'Sokoto North V']],
    ['Sokoto South', ['Sokoto South I', 'Sokoto South II', 'Sokoto South III', 'Sokoto South IV', 'Sokoto South V']],
    ['Tambuwal', ['Tambuwal I', 'Tambuwal II', 'Tambuwal III', 'Tambuwal IV', 'Tambuwal V']],
    ['Tangaza', ['Tangaza I', 'Tangaza II', 'Tangaza III', 'Tangaza IV']],
    ['Tureta', ['Tureta I', 'Tureta II', 'Tureta III', 'Tureta IV']],
    ['Wamako', ['Wamako I', 'Wamako II', 'Wamako III', 'Wamako IV', 'Wamako V']],
    ['Wurno', ['Wurno I', 'Wurno II', 'Wurno III', 'Wurno IV', 'Wurno V']],
    ['Yabo', ['Yabo I', 'Yabo II', 'Yabo III', 'Yabo IV']],
  ]),
  makeState('taraba', 'Taraba', [
    ['Ardo Kola', ['Ardo Kola I', 'Ardo Kola II', 'Ardo Kola III', 'Ardo Kola IV']],
    ['Bali', ['Bali I', 'Bali II', 'Bali III', 'Bali IV', 'Bali V']],
    ['Donga', ['Donga I', 'Donga II', 'Donga III', 'Donga IV']],
    ['Gashaka', ['Gashaka I', 'Gashaka II', 'Gashaka III', 'Gashaka IV']],
    ['Gassol', ['Gassol I', 'Gassol II', 'Gassol III', 'Gassol IV', 'Gassol V']],
    ['Ibi', ['Ibi I', 'Ibi II', 'Ibi III', 'Ibi IV']],
    ['Jalingo', ['Jalingo I', 'Jalingo II', 'Jalingo III', 'Jalingo IV', 'Jalingo V']],
    ['Karim Lamido', ['Karim Lamido I', 'Karim Lamido II', 'Karim Lamido III', 'Karim Lamido IV', 'Karim Lamido V']],
    ['Kurmi', ['Kurmi I', 'Kurmi II', 'Kurmi III', 'Kurmi IV']],
    ['Lau', ['Lau I', 'Lau II', 'Lau III', 'Lau IV']],
    ['Sardauna', ['Sardauna I', 'Sardauna II', 'Sardauna III', 'Sardauna IV', 'Sardauna V']],
    ['Takum', ['Takum I', 'Takum II', 'Takum III', 'Takum IV', 'Takum V']],
    ['Ussa', ['Ussa I', 'Ussa II', 'Ussa III', 'Ussa IV']],
    ['Wukari', ['Wukari I', 'Wukari II', 'Wukari III', 'Wukari IV', 'Wukari V']],
    ['Yorro', ['Yorro I', 'Yorro II', 'Yorro III', 'Yorro IV']],
    ['Zing', ['Zing I', 'Zing II', 'Zing III', 'Zing IV', 'Zing V']],
  ]),
  makeState('yobe', 'Yobe', [
    ['Bade', ['Bade I', 'Bade II', 'Bade III', 'Bade IV', 'Bade V']],
    ['Bursari', ['Bursari I', 'Bursari II', 'Bursari III', 'Bursari IV']],
    ['Damaturu', ['Damaturu I', 'Damaturu II', 'Damaturu III', 'Damaturu IV', 'Damaturu V']],
    ['Fika', ['Fika I', 'Fika II', 'Fika III', 'Fika IV', 'Fika V']],
    ['Fune', ['Fune I', 'Fune II', 'Fune III', 'Fune IV']],
    ['Geidam', ['Geidam I', 'Geidam II', 'Geidam III', 'Geidam IV', 'Geidam V']],
    ['Gujba', ['Gujba I', 'Gujba II', 'Gujba III', 'Gujba IV']],
    ['Gulani', ['Gulani I', 'Gulani II', 'Gulani III', 'Gulani IV']],
    ['Jakusko', ['Jakusko I', 'Jakusko II', 'Jakusko III', 'Jakusko IV']],
    ['Karasuwa', ['Karasuwa I', 'Karasuwa II', 'Karasuwa III', 'Karasuwa IV']],
    ['Machina', ['Machina I', 'Machina II', 'Machina III', 'Machina IV']],
    ['Nangere', ['Nangere I', 'Nangere II', 'Nangere III', 'Nangere IV']],
    ['Nguru', ['Nguru I', 'Nguru II', 'Nguru III', 'Nguru IV', 'Nguru V']],
    ['Potiskum', ['Potiskum I', 'Potiskum II', 'Potiskum III', 'Potiskum IV', 'Potiskum V']],
    ['Tarmuwa', ['Tarmuwa I', 'Tarmuwa II', 'Tarmuwa III', 'Tarmuwa IV']],
    ['Yunusari', ['Yunusari I', 'Yunusari II', 'Yunusari III', 'Yunusari IV']],
    ['Yusufari', ['Yusufari I', 'Yusufari II', 'Yusufari III', 'Yusufari IV']],
  ]),
  makeState('zamfara', 'Zamfara', [
    ['Anka', ['Anka I', 'Anka II', 'Anka III', 'Anka IV', 'Anka V']],
    ['Bakura', ['Bakura I', 'Bakura II', 'Bakura III', 'Bakura IV']],
    ['Birnin Magaji/Kiyaw', ['Birnin Magaji I', 'Birnin Magaji II', 'Birnin Magaji III', 'Birnin Magaji IV']],
    ['Bukkuyum', ['Bukkuyum I', 'Bukkuyum II', 'Bukkuyum III', 'Bukkuyum IV', 'Bukkuyum V']],
    ['Bungudu', ['Bungudu I', 'Bungudu II', 'Bungudu III', 'Bungudu IV', 'Bungudu V']],
    ['Gummi', ['Gummi I', 'Gummi II', 'Gummi III', 'Gummi IV', 'Gummi V']],
    ['Gusau', ['Gusau I', 'Gusau II', 'Gusau III', 'Gusau IV', 'Gusau V', 'Gusau VI']],
    ['Kaura Namoda', ['Kaura Namoda I', 'Kaura Namoda II', 'Kaura Namoda III', 'Kaura Namoda IV', 'Kaura Namoda V']],
    ['Maradun', ['Maradun I', 'Maradun II', 'Maradun III', 'Maradun IV']],
    ['Maru', ['Maru I', 'Maru II', 'Maru III', 'Maru IV', 'Maru V']],
    ['Shinkafi', ['Shinkafi I', 'Shinkafi II', 'Shinkafi III', 'Shinkafi IV', 'Shinkafi V']],
    ['Talata Mafara', ['Talata Mafara I', 'Talata Mafara II', 'Talata Mafara III', 'Talata Mafara IV', 'Talata Mafara V']],
    ['Tsafe', ['Tsafe I', 'Tsafe II', 'Tsafe III', 'Tsafe IV']],
    ['Zurmi', ['Zurmi I', 'Zurmi II', 'Zurmi III', 'Zurmi IV', 'Zurmi V']],
  ]),
];
